### ISSUE TITLE
Endpoints Description Error

### ISSUE THREAD

**Issue by manastopulos** [MatiasAnas/notes-api#2]
All the routes with /{id} are wrong in the description. They shouldn't be /note/{id}, they should be /notes/{id}.
![Captura de pantalla de 2021-05-17 09-11-17](https://user-images.githubusercontent.com/66271836/118486340-ddd38d00-b6ef-11eb-879a-1135ad37545b.png)

**Comment by MatiasAnas** [comment]
Fixed!
