### ISSUE TITLE
Some fixes due to training feedback

### ISSUE THREAD

**Issue by manastopulos** [MatiasAnas/notes-api#3]
* Add "# No Title" label when it is absent.
![Captura de pantalla de 2021-08-11 16-38-48](https://user-images.githubusercontent.com/66271836/129420388-6550f5e5-b216-4837-8f09-d006583ccb8f.png)
* Return the updated note in the PUT and PATCH services, like in the POST.
![Captura de pantalla de 2021-08-11 16-39-06](https://user-images.githubusercontent.com/66271836/129420468-2c12522f-e867-419d-ba29-81c9935003b8.png)
Also, refactor the controller method to update a note, it looks very complex.
* It will me nice to have the creation and update time for the notes.

**Comment by MatiasAnas** [comment]
Done in https://github.com/MatiasAnas/notes-api/pull/4
